# Generated by Django 5.2.5 on 2025-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('count', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='spices/')),
            ],
        ),
    ]
