# Generated by Django 5.2.5 on 2025-08-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_contactmessage_pairing_product_spice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spicecollection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='spicecollection',
            name='updated_at',
        ),
    ]
