# Generated by Django 5.2.5 on 2025-08-30 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_spicecollection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spicecollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 30, 9, 29, 33, 961895, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spicecollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
