# Generated by Django 5.2.5 on 2025-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_spicecollection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='categories',
            field=models.CharField(help_text='Example: Veg, Non-Veg', max_length=255),
        ),
    ]
