# Generated by Django 5.2.5 on 2025-09-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pairing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='categories',
            field=models.CharField(max_length=255),
        ),
    ]
