# Generated by Django 5.2.5 on 2025-09-01 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pairing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='vegan',
            field=models.CharField(default=datetime.datetime(2025, 9, 1, 10, 9, 8, 79537, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
