# Generated by Django 5.2.5 on 2025-09-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_usersignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
