# Generated by Django 5.2.5 on 2025-12-19 06:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('shift', models.CharField(choices=[('morning', 'Morning (6AM-2PM)'), ('afternoon', 'Afternoon (2PM-10PM)'), ('night', 'Night (10PM-6AM)')], max_length=50)),
                ('gate', models.CharField(default='Main Gate', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('driving_license', 'Driving License'), ('passport', 'Passport'), ('company_id', 'Company ID'), ('aadhar', 'Aadhar Card'), ('voter_id', 'Voter ID'), ('other', 'Other')], max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('security_breach', 'Security Breach'), ('unauthorized_access', 'Unauthorized Access'), ('theft', 'Theft'), ('violence', 'Violence/Threat'), ('fraud', 'Fraudulent Activity'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blacklist_photos/')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.securityguard')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company', models.CharField(max_length=100)),
                ('visitor_type', models.CharField(choices=[('guest', 'Guest'), ('contractor', 'Contractor/Vendor'), ('delivery', 'Delivery Person'), ('interview', 'Interview Candidate'), ('emergency', 'Emergency Services'), ('other', 'Other')], default='guest', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('id_type', models.CharField(choices=[('driving_license', 'Driving License'), ('passport', 'Passport'), ('company_id', 'Company ID'), ('aadhar', 'Aadhar Card'), ('voter_id', 'Voter ID'), ('other', 'Other')], max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='id_photos/')),
                ('purpose', models.CharField(max_length=200)),
                ('meeting_location', models.CharField(blank=True, max_length=100)),
                ('expected_duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('items_brought', models.JSONField(blank=True, default=list)),
                ('security_notes', models.TextField(blank=True)),
                ('signature', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='checked_in', max_length=20)),
                ('badge_number', models.CharField(blank=True, max_length=20)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='app.securityguard')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='app.securityguard')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='app.host')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('photo_captured', 'Photo Captured'), ('id_verified', 'ID Verified'), ('host_notified', 'Host Notified'), ('badge_printed', 'Badge Printed'), ('status_changed', 'Status Changed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.securityguard')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['visitor_id'], name='app_visitor_visitor_9d4c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['check_in_time'], name='app_visitor_check_i_ed520c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['status'], name='app_visitor_status_d72e18_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['host'], name='app_visitor_host_id_cdfcd9_idx'),
        ),
    ]
