# Generated by Django 5.2.5 on 2026-04-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merchantuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantUser',
        ),
    ]
